Minor changes to fix switching of resolutions.
EmuELEC/EmuELEC pull request #703
Opened 2021-09-08 01:05 UTC by Langerz82

A more cleaner way of switching Resolutions, so screen corruption does not occur.

2021-09-08 01:06 UTC, Langerz82 commented on packages/sx05re/tools/sysutils/gptokeyb/package.mk
> +PKG_VERSION="ded03731ccf8e65e855dd776aade021425afc53b"
Update gptokeyb package build.

2021-09-08 01:09 UTC, Langerz82 commented
In the former code, when an error occurs and TvTextViewer is shown the display can corrupt. This code is much cleaner. It blanks the buffers and restores only when the Res is fully switched, and no need to call the show splash twice.

2021-09-08 21:17 UTC, shantigilbert requested changes

2021-09-09 01:44 UTC, Langerz82 commented on packages/sx05re/tools/sysutils/gptokeyb/package.mk
> +PKG_VERSION="ded03731ccf8e65e855dd776aade021425afc53b"
Done. But yeah please update the gptokeyb version please!

2021-09-09 03:08 UTC, merged

2021-09-09 03:09 UTC, shantigilbert commented
Thank you!